### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by willmoffat** [bboozzoo/mender-backend-cli#8]
Would be great to having a getting started section, it took me a while to figure out the login flow and the position of parameters.

Something like this perhaps:

#### Login
Create `./usertoken`
```
LOGIN=will@muuselabs.com
PASS=xxx
SERVICE=https://mender.muuselabs.com 
mender-backend -s $SERVICE user login -u $LOGIN -p $PASS
```

#### List artifacts
`mender-backend -u usertoken -s $SERVICE artifact list`

#### List deployments
`mender-backend  -u usertoken -s $SERVICE deployment find '*' > deployments.json`

#### Use jq to filter output:
`cat deployments.json | jq '.[] | {name, status, artifact_name, finished}'`

**Comment by bboozzoo** [comment]
Thanks for the report. Unfortunately I no longer work on mender, see here for further instructions https://github.com/bboozzoo/mender-backend-cli/issues/9#issuecomment-342393165
